-- ---------------------------------------------------------------------
-- PHASE 60 — agreements and invoices.
--
-- 1. client_agreements: one per client. What the client has agreed to pay for:
--    packages picked from the agency's catalog (Team & settings → Packages &
--    billing), each with its price in BDT, monthly or one-off, and what the
--    agency delivers for it. Saving a changed agreement raises `version`; the
--    owner signs a version (typed name, ticked "I agree", time and IP kept),
--    so a changed agreement is signed again.
--
-- 2. invoices: made by hand by the agency, numbered across every client
--    (INV-0001…), shown to the owner in their app, marked paid by the agency.
--
-- The catalog and the agency's invoice details live in system_settings
-- (billing_packages, billing_profile), like the other settings.
--
-- Run in the Supabase SQL editor before deploying the phase-60 server.
-- Idempotent.
-- ---------------------------------------------------------------------

create table if not exists public.client_agreements (
    id               uuid primary key default gen_random_uuid(),
    client_id        uuid not null unique references public.clients(id) on delete cascade,
    items            jsonb not null default '[]'::jsonb,   -- [{ name, billing: monthly|one_off, price, description, deliverables: [text] }]
    terms            text check (terms is null or char_length(terms) <= 8000),
    start_date       date,
    version          integer not null default 1,
    signed_version   integer,                              -- the version the owner accepted; null = never
    signed_name      text,
    signed_at        timestamptz,
    signed_by        uuid,
    signed_ip        text,
    updated_by       uuid,
    created_at       timestamptz not null default now(),
    updated_at       timestamptz not null default now()
);
alter table public.client_agreements enable row level security;
comment on table public.client_agreements is
    'What a client agreed to pay for and what the agency delivers. The owner signs a version; a changed agreement is signed again.';

create table if not exists public.invoices (
    id               uuid primary key default gen_random_uuid(),
    client_id        uuid not null references public.clients(id) on delete cascade,
    invoice_number   bigint generated by default as identity,
    issue_date       date not null default current_date,
    due_date         date,
    items            jsonb not null default '[]'::jsonb,   -- [{ text, qty, price }]
    total            numeric(14, 2) not null default 0,
    status           text not null default 'unpaid' check (status in ('unpaid', 'paid', 'void')),
    paid_at          timestamptz,
    paid_note        text check (paid_note is null or char_length(paid_note) <= 300),
    notes            text check (notes is null or char_length(notes) <= 2000),
    created_by       uuid,
    created_at       timestamptz not null default now(),
    updated_at       timestamptz not null default now()
);
create unique index if not exists invoices_number_idx on public.invoices (invoice_number);
create index if not exists invoices_client_idx on public.invoices (client_id, issue_date desc);
alter table public.invoices enable row level security;
comment on table public.invoices is
    'An invoice the agency made for a client. Numbered across every client; shown to the owner unless void.';
