-- ---------------------------------------------------------------------
-- PHASE 48 — tasks as proper issues: a key, a priority, a real
-- description with pictures.
--
--   client_tasks.task_number   a running number, shown as a key (HC-12),
--                              so a task can be named in a message
--   client_tasks.priority      lowest · low · medium · high · highest
--   client_tasks.notes         the description: up to 20,000 characters
--                              (pictures sit in it as short references)
--   client_task_media          one row per picture pasted into a task's
--                              description or a comment. The file itself is
--                              in the private storage bucket "task-media"
--                              (the server makes it); a picture is only ever
--                              handed out as a short-lived signed link, to
--                              someone who may read the task.
--
-- Run in the Supabase SQL editor before deploying the phase-48 server.
-- Idempotent.
-- ---------------------------------------------------------------------

alter table public.client_tasks add column if not exists priority text not null default 'medium';
alter table public.client_tasks drop constraint if exists client_tasks_priority_check;
alter table public.client_tasks add constraint client_tasks_priority_check
    check (priority in ('lowest', 'low', 'medium', 'high', 'highest'));

alter table public.client_tasks add column if not exists task_number bigint generated by default as identity;
create unique index if not exists idx_client_tasks_number on public.client_tasks (task_number);

alter table public.client_tasks drop constraint if exists client_tasks_notes_check;
alter table public.client_tasks add constraint client_tasks_notes_check
    check (notes is null or char_length(notes) <= 20000);

alter table public.client_task_comments drop constraint if exists client_task_comments_body_check;
alter table public.client_task_comments add constraint client_task_comments_body_check
    check (char_length(body) between 1 and 4000);

create table if not exists public.client_task_media (
    id            uuid primary key default gen_random_uuid(),
    client_id     uuid not null references public.clients(id) on delete cascade,
    task_id       uuid references public.client_tasks(id) on delete cascade,   -- set once the task is saved
    path          text not null,                                               -- the object's path in the task-media bucket
    content_type  text not null,
    bytes         integer not null,
    uploaded_by   uuid,
    created_at    timestamptz not null default now()
);
create index if not exists idx_client_task_media_task   on public.client_task_media (task_id);
create index if not exists idx_client_task_media_client on public.client_task_media (client_id, created_at);
alter table public.client_task_media enable row level security;

comment on table public.client_task_media is
    'A picture pasted into a task or a comment. The bytes are in the private task-media bucket; the server hands out signed links only to people who may read the task.';
